title: Awesome Blog
email: example@example.com
description: This blog is awesome!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

permalink: /:title

exclude:
  - Gemfile
  - Gemfile.lock
